"""initial_schema_rebuild

Revision ID: 567305f96bd1
Revises: 
Create Date: 2026-05-25 01:27:16.187563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '567305f96bd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False, comment='Raw transcription text'),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('ata_chapter', sa.String(length=50), nullable=True),
    sa.Column('action_performed', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False, comment='Verification compliance checks outcome (PASS / FAIL)'),
    sa.Column('validation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Descriptions of spec mismatch failures'),
    sa.Column('references_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='AMM vector search reference metadata chunks'),
    sa.Column('compliance_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dynamic compliance parameters parsed from task'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_created_at'), 'maintenance_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_records_part_name'), 'maintenance_records', ['part_name'], unique=False)
    op.create_index(op.f('ix_maintenance_records_validation_status'), 'maintenance_records', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_validation_status'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_part_name'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_created_at'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
